version: "3"
services:
  users:
    build:
      context: "."
      dockerfile: "./services/users/Dockerfile"
    depends_on:
      - users-db
    ports:
      - "3010:3010"
    volumes:
      - ./services/users:/opt/app

  users-db:
    environment:
      - MONGO_ROOT_PASSWORD=password
      - MONGO_DATABASE=db
    image: mongo:latest
    ports:
     - "3011:27017"

  tickets-handler:
    build:
      context: "."
      dockerfile: "./services/tickets-handler/Dockerfile"
    depends_on:
      - tickets-handler-db
    ports:
      - "3020:3020"
    volumes:
      - ./services/tickets-handler:/opt/app

  tickets-handler-db:
    environment:
      - MONGO_ROOT_PASSWORD=password
      - MONGO_DATABASE=db
    image: mongo:latest
    ports:
     - "3021:27017"
      